<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head profile="http://selenium-ide.openqa.org/profiles/test-case">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="selenium.base" href="http://localhost/" />
<title>full</title>
</head>
<body>
<table cellpadding="1" cellspacing="1" border="1">
<thead>
<tr><td rowspan="1" colspan="3">full</td></tr>
</thead><tbody>
<tr>
	<td>open</td>
	<td>/xampp/CS402Website/</td>
	<td></td>
</tr>
<tr>
	<td>type</td>
	<td>name=firstname</td>
	<td>ali</td>
</tr>
<tr>
	<td>type</td>
	<td>name=lastname</td>
	<td>veli</td>
</tr>
<tr>
	<td>click</td>
	<td>id=sex-0</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=sex-1</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=exp-0</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=exp-1</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=exp-2</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=exp-3</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=exp-4</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=exp-5</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=exp-6</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=profession-0</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=profession-1</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=tool-0</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=tool-1</td>
	<td></td>
</tr>
<tr>
	<td>click</td>
	<td>id=tool-2</td>
	<td></td>
</tr>
<tr>
	<td>clickAndWait</td>
	<td>id=submit</td>
	<td></td>
</tr>

</tbody></table>
</body>
</html>
