// Generated by GraphWalker (http://www.graphwalker.org)
package org.myorg.testautomation;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "org/myorg/testautomation/Login.graphml")
public interface Login {

    @Edge()
    void e_InvalidCredentials();

    @Vertex()
    void v_LoginPrompted();

    @Edge()
    void e_ToggleRememberMe();

    @Edge()
    void e_Exit();

    @Edge()
    void e_ValidPremiumCredentials();

    @Edge()
    void e_Close();

    @Edge()
    void e_Logout();

    @Edge()
    void e_Init();

    @Vertex()
    void v_Browse();

    @Edge()
    void e_StartClient();

    @Vertex()
    void v_ClientNotRunning();
}
